version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
   ApplicationStop:
    - location: scripts/deregister_from_elb.sh
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/register_with_elb.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
