name: Version Pooler

on:
  push:

jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Test Run
        run: echo "hello world"
      - name: Trigger the build
        run: |
                curl -X POST \
                 -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/ainzizou/testCode/dispatches \
                 -d '{"event_type":"build","client_payload":{"unit":false,"integration":true}}'

